file_dir: /nesi/nobackup/uoo03104/output_files_nocrocus
ob_dir: /nesi/nobackup/uoo03104/validation_data/streamgagedata
ob_csv: stream_conc.csv
save_dir: /nesi/nobackup/uoo03104/output_files_nocrocus
station_names: [aiken_f5, bohner_b5, canada_f1, lawson_b3, onyx_vnda, onyx_lwright]


